version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@1.3.2

executors:
  default:
    docker:
      - image: circleci/node:10.17.0
      - image: circleci/python:2.7

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
      - run: npm run build

  deploy:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/install
      - npm_install
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          from: dist
          to: s3://circieci-s3-test/dist
          overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: master
